# Generated by Django 5.0.6 on 2024-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='img',
            field=models.ImageField(null=True, upload_to='product_type_images/', verbose_name='Картинка'),
        ),
    ]
