# Generated by Django 5.0.6 on 2024-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producttype_description_alter_producttype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypeimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_type_images/', verbose_name='Изображение'),
        ),
    ]
